# Generated by Django 5.1.4 on 2025-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
