# Generated by Django 5.1.4 on 2025-01-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0004_car_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
