# Generated by Django 5.1.4 on 2025-01-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_car_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
