# Generated by Django 5.1.4 on 2025-01-10 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0006_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
